#pragma once
#include <array>

constexpr std::array<const char*,12> err_msg_log = {
    "Directory \"{0}\" creation denied.",
    "Missing \"data{0}\" file in destination directory \"{1}\".",
    "File \"{0}\" access denied by permissions.",
    "Trying to open a not-file \"{0}\".",
    "Cannot access path: \"{0}\".",
    "File \"{0}\" don't exists.",
    "Cannot open file \"{0}\".",
    "Invalid path of directories \"{0}\".",
    "\"{0}\" is not a directory.",
    "\"{0}\" is not a file.",
    "Format file {0} is corrupted.",
    "Error at indexing: file {0}, position {1}"
};

constexpr std::array<const char*,50> err_msg={
    "Process successed",
    "Internal error",
    "Incorrect argument: date interval",
    "Incorrect argument: date. Arg: {0}",
    "Incorrect argument: coordinate position",
    "Incorrect argument: rectangle",
    "Error at command input {0}",
    "Too few arguments",
    "Too many arguments",
    "Incorrect argument \"{0}\". Already choosen mode: \"{1}\"",
    "Directory \"{0}\" creation denied",
    "File \"{0}\" access denied by permissions",
    "Trying to open a not-file \"{0}\"",
    "Cannot access path: \"{0}\"",
    "File \"{0}\" don't exists",
    "Cannot open file \"{0}\"",
    "Invalid path of directories \"{0}\"",
    "\"{0}\" is not a directory",
    "\"{0}\" is not a file",
    "Ignoring argument \"{0}\"",
    "Already existing configuration name",
    "Configuration name {0} doesn't exists",
    "Directory \"{0}\" don't exists",
    "Unknown format \"{0}\"",
    "Undefined file format",
    "Undefined value",
    "Integrity violated",
    "Invalid index order",
    "Invalid host \"{0}\"",
    "Connection error",
    "Connection error with {0}",
    "Invalid request",
    "Sending message error",
    "Connection closed",
    "Interrupted",
    "Receiving message error",
    "{0} is not regular file or directory",
    "Invalid value \"{0}\" of parameter \"{1}\"",
    "Invalid argument",
    "Transaction refused",
    "Invalid credentials",
    "Deserialization error",
    "Serialization error",
    "Server error",
    "Requested data not found",
    "Not enough buffer size",
    "Timeout of operation",
    "The file {0} is corrupted or has invalid format",
    "Data version {0} is unreachable for this Mashroom version",
    "File {0} reading error"
};