#pragma once
#include <cstddef>
#include <cinttypes>
#include <string>

enum class ErrorCodeLog : uint{
    CREATE_DIR_X1_DENIED,
    BIN_WITH_FMT_X1_FILE_MISS_IN_DIR_X2,
    FILE_X1_PERM_DENIED,
    TRY_OPEN_NOT_FILE_X1,
    CANNOT_ACCESS_PATH_X1,
    FILE_X1_DONT_EXISTS,
    CANNOT_OPEN_FILE_X1,
    INVALID_PATH_OF_DIRECTORIES_X1,
    X1_IS_NOT_DIRECTORY,
    X1_IS_NOT_FILE,
    FORMAT_FILE_CORRUPTED,
    CAPITALIZE_ERR_X1_FILE_X2_POS
};

enum class ErrorCode : uint8_t{
    NONE = 0,
    INTERNAL_ERROR,
    INCORRECT_DATE_INTERVAL,
    INCORRECT_DATE,
    INCORRECT_COORD,
    INCORRECT_RECT,
    COMMAND_INPUT_X1_ERROR,
    TO_FEW_ARGUMENTS,
    TO_MANY_ARGUMENTS,
    INCOR_ARG_X1_ALREADY_CHOOSEN_MODE_X2,
    CREATE_DIR_X1_DENIED,
    FILE_X1_PERM_DENIED,
    TRY_OPEN_NOT_FILE_X1,
    CANNOT_ACCESS_PATH_X1,
    FILE_X1_DONT_EXISTS,
    CANNOT_OPEN_FILE_X1,
    INVALID_PATH_OF_DIRECTORIES_X1,
    X1_IS_NOT_DIRECTORY,
    X1_IS_NOT_FILE,
    IGNORING_VALUE_X1,
    ALREADY_EXISTING_CONFIG_NAME,
    DIRECTORY_X1_DONT_EXISTS,
    UNKNOWN_X1_FORMAT_FILE,
    UNDEFINED_FORMAT_FILE,
    UNDEFINED_VALUE,
    INTEGRITY_VIOLATED,
    INVALID_CAPITALIZE_ORDER,
    INVALID_HOST_X1,
    CONNECTION_ERROR,
    CONNECTION_ERROR_WITH_X1,
    INVALID_CLIENT_REQUEST,
    SENDING_MESSAGE_ERROR,
    CONNECTION_CLOSED,
    INTERRUPTED,
    RECEIVING_MESSAGE_ERROR,
    X1_IS_NOT_REGULAR_FILE_OR_DIRECTORY,
    INVALID_VALUE_X1_OF_PARAMETER_X2,
    INVALID_ARGUMENT,
    TRANSACTION_REFUSED,
    INVALID_CREDENTIALS,
    DESERIALIZATION_ERROR,
    SERIALIZATION_ERROR
};

enum class AT_ERROR_ACTION{
    CONTINUE,
    ABORT
};